[package]
name = "overlinejunior/state-machine"
version = "2.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"
author = "Over"
exclude = ["selene.toml", "roblox.toml"]


[dependencies]
