[package]
name = "overlinejunior/state-machine"
version = "2.4.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"
author = "Over"
description = "An immutable class for handling the state of things."
exclude = ["selene.toml", "roblox.toml"]


[dependencies]
Option = "sleitnick/option@1.0.4"
